Feature/db config
navikt/doknotifikasjon pull request #31
Opened 2020-10-06 09:55 UTC by HeidiElisabeth

2020-10-06 10:54 UTC, joakibj requested changes

2020-10-06 10:54 UTC, joakibj commented on app/src/main/resources/application-local.properties
> +#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
Sjekk med Spring Boot sin reference documentation. Dette burde sannsynligvis settes.

2020-10-06 10:54 UTC, joakibj commented on app/src/main/resources/application-local.properties
> +#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
Her må man undersøke hva dette betyr.

2020-10-06 10:54 UTC, joakibj commented on core/pom.xml
> +            <artifactId>spring-boot</artifactId>
Hvorfor har man denne her?

2020-10-06 10:54 UTC, joakibj commented on core/pom.xml
> +            <version>2.3.1.RELEASE</version>
Alle versjoner i underliggende moduler burde ha innslag i `dependencyManagement`. Dette for å redusere risiko for feil dependencies.

2020-10-06 10:54 UTC, joakibj commented on core/pom.xml
> +            <version>6.4.4</version>
For flyway skal vi bruke det som Spring Boot bundler. Se dokumentasjon https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#dependency-versions-coordinates
Vi ønsker ikke konflikt mellom flyway versjon og Spring Boot versjon.

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/config/DatabaseConfig.java
> +//@EnableJpaRepositories(basePackages = "no.nav.doknotifikasjon")
Husk å kommentere denne inn

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/config/DatabaseConfig.java
> +		config.setMinimumIdle(1);
Når man har med databaser å gjøre, så er det alltid lurt å tune pooling. https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/config/DatabaseConfig.java
> +														   @Value(CLUSTER_NAME) final String cluster) {
Her var det noe rar formattering

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/config/DatabaseConfig.java
> +		if (cluster.contains("dev-fss")) {
Se om dette kan løses med config i stedet for if test else prod

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/Notifikasjon.java
> +	private Integer notifikasjonId;
Foreslår at denne kalles bare `id`. Tabellene er såpass enkle.

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.0.0__Create_doknotifikasjon_tables.sql
> +    NOTIFIKASJON_ID             NUMBER NOT NULL,
`NUMBER` er ikke en postgresql numeric datatype. Se https://www.postgresql.org/docs/9.6/datatype-numeric.html

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.0.0__Create_doknotifikasjon_tables.sql
> +    NOTIFIKASJON_ID             NUMBER NOT NULL,
Denne kan gjerne hete `ID`

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/Notifikasjon.java
> +	@Column(name = "BESTILLING_ID")
Anbefaler å sette column length her hvis det er en begrensning i den faktiske databasen. Dette vil hjelpe for test

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/Notifikasjon.java
> +	private String mottakerIdType;
Dette skal være en `Enumeration`. Se JPA dokumentasjon for dette

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/Notifikasjon.java
> +	private String status;
Dette burde være en `Enumeration`.

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/Notifikasjon.java
> +	private LocalDate nesteRenotifikasjonDato;
Her mener jeg det må noe mer til slik at denne skal bli mappet riktig til en dato. Se `Temporal` annotasjonen.

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/Notifikasjon.java
> +	private LocalDate opprettetDato;
`@Temporal` og `LocalDateTime` ?

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/Notifikasjon.java
> +	private LocalDate endretDato;
`@Temporal` og `LocalDateTime` ?

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/NotifikasjonDistribusjon.java
> +	private Integer notifikasjonDistribusjonId;
Kan denne hete `id` også ?

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/NotifikasjonDistribusjon.java
> +	private String status;
`@Enumerated` ?

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/NotifikasjonDistribusjon.java
> +	private String notifikasjonId;
Fremmednøkler behøver man ikke eksponere her. Da dette blir satt av JPA når man oppretter en `NotifikasjonDistribusjon` for en `Notifikasjon`

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/Notifikasjon.java
> +}
Her savner jeg en relasjon til `NotifikasjonDistribusjon`? Skal ikke dette være en en-til-mange relasjon?

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/NotifikasjonDistribusjon.java
> +	private String notifikasjonKanal;
Kan man kalle denne bare `kanal` ?

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/NotifikasjonDistribusjon.java
> +	private String notifikasjonKanal;
Dette skal være en `Enumeration`. Hvis den skal referere til en kodeverkstabell så må denne konfigurasjonen rettes

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/NotifikasjonDistribusjon.java
> +	private LocalDate notifikasjonSendtDato;
Kan denne hete bare `sendtDato` ?

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/NotifikasjonDistribusjon.java
> +	private LocalDate notifikasjonSendtDato;
Dette burde være en `LocalDateTime`

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/NotifikasjonDistribusjon.java
> +	private LocalDate opprettetDato;
Dette burde være en `LocalDateTime`

2020-10-06 10:54 UTC, joakibj commented on core/src/main/java/no/nav/doknotifikasjon/model/NotifikasjonDistribusjon.java
> +	private LocalDate endretDato;
Dette burde være en `LocalDateTime`

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.0.0__Create_doknotifikasjon_tables.sql
> +    BESTILLING_ID               VARCHAR(20) UNIQUE NOT NULL,
Denne burde utvides til `VARCHAR(40)`

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.0.0__Create_doknotifikasjon_tables.sql
> +CREATE TABLE T_NOTIFIKASJON
Jeg foreslår at disse reformatteres til PostgreSQL dialekten. Det skal være støtte for dette i IntelliJ. Typisk så er SQL med store bokstaver gammeldags

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.0.0__Create_doknotifikasjon_tables.sql
> +    K_MOTTAKER_ID_TYPE          VARCHAR(20) NOT NULL,            --Kodeverk K_MOTTAKER_ID_TYPE
Her må man ha en skranke mot `T_K_MOTTAKER_ID_TYPE`

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.0.0__Create_doknotifikasjon_tables.sql
> +CREATE SEQUENCE NOTIFIKASJON_ID_SEQ;
Les dokumentasjon på å lage sequences. Her kan det være lurt å minimum ha noe cache slik at JPA kan bruke det

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.0.0__Create_doknotifikasjon_tables.sql
> +CREATE INDEX IDX_StatusAntallRenotifikasjonerNesteRenotifikasjonDato ON T_NOTIFIKASJON(K_STATUS, ANTALL_RENOTIFIKASJONER, NESTE_RENOTIFIKASJON_DATO);
Navnet kan være kortere. Sjekk hva som er standard for postgresql verden. Primer https://use-the-index-luke.com/

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.0.0__Create_doknotifikasjon_tables.sql
> +CREATE TABLE T_NOTIFIKASJON
Foreslår versjonering av flyway følger konvensjon 1, 2, 3 osv. Gjør det enkelt

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.0.0__Create_doknotifikasjon_tables.sql
> +CREATE TABLE T_NOTIFIKASJON
Foreslår at første script puttes i samme fil

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.0.0__Create_doknotifikasjon_tables.sql
> +CREATE SEQUENCE NOTIFIKASJON_DISTRIBUSJON_ID_SEQ;
Sequence tuning her.

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.1.0__Create_doknotifikasjon_kodeverk.sql
> +CREATE TABLE T_K_MOTTAKER_ID_TYPE       --???????
Denne kan hete noe annet

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.1.0__Create_doknotifikasjon_kodeverk.sql
> +    K_MOTTAKER_ID_TYPE  VARCHAR(20) NOT NULL,
Kan navnet her forenkles?

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.1.0__Create_doknotifikasjon_kodeverk.sql
> +
For alle tabellene over så må det defineres skranker / constraints i kolonnene i Notifikasjon og NotifikasjonDistribusjon

2020-10-06 10:54 UTC, joakibj commented on core/src/main/resources/db/migration/V1.1.0__Create_doknotifikasjon_kodeverk.sql
> +INSERT INTO T_K_STATUS(K_STATUS) VALUES ('OPPRETTET');
Mener det skal være mulig å oppgi flere verdier i `VALUES`

2020-10-07 10:52 UTC, TimAa-nav-dev commented on app/src/main/java/no/nav/doknotifikasjon/Application.java
> +import no.nav.doknotifikasjon.config.ServiceuserAlias;
Har lagt til TDOK-Default.xml til min inteilliji's codeStyle

2020-10-08 13:10 UTC, joakibj requested changes
Ser stort sett greit ut. Eneste er mismatch mellom navn på kolonner i flyway vs JPA `@Column` definisjonen

2020-10-08 13:10 UTC, joakibj commented on knot001/pom.xml
> +            <groupId>org.projectlombok</groupId>
Denne behøver provided scope eller legges til i `<dependencies >` på rot pom

2020-10-08 13:10 UTC, joakibj commented on pom.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Se gjerne på tabs vs spaces her. Sjekk om du bruker vår codestyle (vi skal bruke spaces)

2020-10-08 13:10 UTC, joakibj commented on core/src/test/java/no/nav/doknotifikasjon/repository/NotifikasjonRepositoryTest.java
> +		notifikasjonDistribusjonRepository.saveAndFlush(createNotifikasjonDistribusjonWithNotifikasjonId(notifikasjon));
Hvis en-til-mange relasjonen er satt opp riktig i JPA så skal det ikke være behov for å ta save på notifikasjondistribusjonen

2020-10-08 13:10 UTC, joakibj commented on core/src/test/java/no/nav/doknotifikasjon/repository/NotifikasjonRepositoryTest.java
> +public class NotifikasjonRepositoryTest {
Dette er stort sett bra

2020-10-08 13:10 UTC, joakibj commented on pom.xml
> +		<logstash-logback-encoder.version>5.1</logstash-logback-encoder.version>
Denne logstash-logback-encoderen er ganske gammel. Sjekk 6.4 versjonen

2020-10-12 08:48 UTC, joakibj approved these changes
Godt nok i denne omgang - jeg ser at lombok ikke er i provided scope og xml formattering bruker tabs og ikke spaces så det ser ut som store endringer er gjort

2020-10-12 08:48 UTC, joakibj commented on pom.xml
> +		</dependency>
scope provided

2020-10-12 11:22 UTC, merged