Feature/kafka
navikt/doknotifikasjon pull request #32
Opened 2020-10-08 14:10 UTC by TimAa-nav-dev

Har lagt til slik at vi har embedded kafka til integerasjons testing og docker med kafka oppsett til lokal utvikling.

2020-10-09 07:32 UTC, HeidiElisabeth requested changes

2020-10-09 07:32 UTC, HeidiElisabeth commented on docker/README.md
> +```
Er dette noe som kan legges i vault som secrets?

2020-10-09 07:32 UTC, HeidiElisabeth commented on docker/docker-compose.yml
> +    - "KAFKA_PASSWORD=itest"
Bør passord være her? Mulig å legge noen av disse config-variablene i secrets?

2020-10-09 07:32 UTC, HeidiElisabeth commented on docker/kafka/kafka_server_jaas.conf
> +   password="itest";
Igjen: Brukernavn og passord i koden - er det dummy-verdier? Eller bør det være i vault?

2020-10-09 07:32 UTC, HeidiElisabeth commented on knot001/src/test/java/no/nav/doknotifikasjon/TestKafkaEventConsumer.java
> +public class TestKafkaEventConsumer extends KafkaIntegrationTest {
Endre navn til KafkaEventConsumerTest?

2020-10-09 07:32 UTC, HeidiElisabeth commented on knot001/src/test/java/no/nav/doknotifikasjon/TestKafkaEventConsumer.java
> +    public void TestDokEventProducer() throws InterruptedException {
Husk beskrivende test-navn: shouldTest...When...

2020-10-09 07:32 UTC, HeidiElisabeth commented on knot001/src/test/java/no/nav/doknotifikasjon/TestKafkaEventConsumer.java
> +    public void TestDokEventProducer() throws InterruptedException {
Er ikke dette samme test som ligger i app? 
Igjen: Hva tester denne egentlig? Ser ingen assertions her?

2020-10-09 07:32 UTC, HeidiElisabeth commented on knot001/src/test/java/no/nav/doknotifikasjon/itest/KafkaIntegrationTest.java
> +public class KafkaIntegrationTest {
Abstract?

2020-10-09 07:52 UTC, TimAa-nav-dev commented on README.md
> +For å kjøre applikasjon kjør med profile naise, local, med system variabler fra her: [System variabler](https://vault.adeo.no/ui/vault/secrets/secret/show/dokument/doknotifikasjon)
Fjernet nais, siden den ikke er nødvendig oppsett til lokalutvikling

2020-10-09 07:53 UTC, TimAa-nav-dev commented on README.md
> +Spørsmål koden eller prosjekttet kan rettes til team dusseldorf på:
Fikset

2020-10-09 07:54 UTC, TimAa-nav-dev commented on README.md
> +* [\#team-dokumentløsning](https://nav-it.slack.com/client/T5LNAMWNA/C6W9E5GPJ)
Takker :) Gjør ting veldig mye enklere for alle. Etter min erfaring er at manglende dokumentasjon ofte fører til mye tids tap.

2020-10-09 07:57 UTC, TimAa-nav-dev commented on knot001/src/test/java/no/nav/doknotifikasjon/itest/KafkaIntegrationTest.java
> +public class KafkaIntegrationTest {
Endrer navnet til EmbededKafkaBrokerAbstract

2020-10-09 07:58 UTC, TimAa-nav-dev commented on knot001/src/test/java/no/nav/doknotifikasjon/TestKafkaEventConsumer.java
> +    public void TestDokEventProducer() throws InterruptedException {
Fjernet

2020-10-09 08:00 UTC, TimAa-nav-dev commented on docker/kafka/kafka_server_jaas.conf
> +   password="itest";
Dette er kode for å få opp kafka miljø lokalt, det er ikke noe med prod-dev å gjøre

2020-10-09 08:01 UTC, TimAa-nav-dev commented on knot001/src/test/java/no/nav/doknotifikasjon/TestKafkaEventConsumer.java
> +public class TestKafkaEventConsumer extends KafkaIntegrationTest {
Fjernet filen

2020-10-09 08:03 UTC, TimAa-nav-dev commented on docker/docker-compose.yml
> +    - "KAFKA_PASSWORD=itest"
Dette er kode for å få opp kafka miljø lokalt, det er ikke noe med prod-dev å gjøre. Ser ikke fordel med å ha det i secret.

2020-10-09 08:07 UTC, TimAa-nav-dev commented on README.md
> +For [dev-fss](https://logs.adeo.no/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(message,envclass,level,application,host),filters:!
fikset

2020-10-09 09:15 UTC, TimAa-nav-dev commented on README.md
> +Ser ikke på inneholdet til feltet sms eller epost når vi mottar kafka eventer på dok-eksternnotifikasjon, applikasjoner sender kafka eventet videre.
Endret teksten til: Tjenestene har ikke noe forhold på inneholdt til feltet epostTekst og smsTekst.

2020-10-09 09:59 UTC, joakibj requested changes
Ser stort sett greit ut. Har bare noen spørsmål

2020-10-09 09:59 UTC, joakibj commented on README.md
> +For [prod-fss](https://logs.adeo.no/goto/3d51098ce277cc4ddf74d8a099f9444b)
Prod url er samme lenken?

2020-10-09 09:59 UTC, joakibj commented on README.md
> +Spørsmål koden eller prosjekttet kan rettes til team dokumentløsning på:
Team Dokumentløsninger, gjelder også linjen under

2020-10-09 09:59 UTC, joakibj commented on app/src/main/resources/application.properties
>  #                  Producer                   #
Er det behov for disse blokkene?

2020-10-09 09:59 UTC, joakibj commented on app/src/main/resources/application.properties
Anbefaler `server.shutdown=graceful`. Se docs https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-graceful-shutdown

2020-10-09 09:59 UTC, joakibj commented on core/pom.xml
> +            <artifactId>junit</artifactId>
Er det behov for junit4?

2020-10-09 09:59 UTC, joakibj commented on core/pom.xml
> +            <artifactId>assertj-core</artifactId>
Denne skal være inkludert i `spring-boot-starter-test`

2020-10-09 09:59 UTC, joakibj commented on knot001/pom.xml
>              <version>1.0-SNAPSHOT</version>
Versjon her burde ligge i `<dependencyManagement>` i rot pom

2020-10-09 10:39 UTC, TimAa-nav-dev commented on README.md
> +For [prod-fss](https://logs.adeo.no/goto/3d51098ce277cc4ddf74d8a099f9444b)
Jeg vil vente til prod er oppe, da vett jeg garantert at den fungere mot prod. Midertidlig er det den samme som dev

2020-10-09 10:40 UTC, TimAa-nav-dev commented on app/src/main/resources/application.properties
>  #                  Producer                   #
Det er ikke nødvendig fra et code perspektiv, men synnes det hjelper å lese strukturen i application.properties.

2020-10-09 10:42 UTC, TimAa-nav-dev commented on README.md
> +Spørsmål koden eller prosjekttet kan rettes til team dokumentløsning på:
Da er det oppdatert

2020-10-09 10:49 UTC, TimAa-nav-dev commented on core/pom.xml
> +            <artifactId>assertj-core</artifactId>
Fikset

2020-10-12 07:41 UTC, HeidiElisabeth requested changes

2020-10-12 07:41 UTC, HeidiElisabeth commented on README.md
> +Tjenestene har ikke noe forhold på inneholdt til feltet epostTekst og smsTekst.
Hva mener du med at "tjenesten har ikke noe forhold på innholdt"?

2020-10-12 07:41 UTC, HeidiElisabeth commented on README.md
> +Lokal utvikling er satt opp slikt at applikasjonen kjøres lokalt og kobles til kafka miljø via et oppsett å docker.
"via et oppsett **på** docker"?

2020-10-12 07:41 UTC, HeidiElisabeth commented on README.md
> +For å kjøre applikasjon kjør med profile local, med system variabler fra her: [System variabler](https://vault.adeo.no/ui/vault/secrets/secret/show/dokument/doknotifikasjon)
Kanskje heller skrive: "med systemvariabler hentet fra vault:"

2020-10-12 07:41 UTC, HeidiElisabeth commented on README.md
> +For produsere kafka meldinger, må man først exec inn på kafka kontaineren ved å bruker docker dashbord, eller ved å kjøre følgende kommando:
"For **å** produsere..."

2020-10-12 07:41 UTC, HeidiElisabeth commented on README.md
> +Avro skjema se til dette repo: [avro skjema](https://github.com/navikt/doknotifikasjon-schemas)
Kan du forklare hva du skal bruke Avro skjema til?

2020-10-12 07:41 UTC, HeidiElisabeth commented on README.md
> +Spørsmål koden eller prosjekttet kan rettes til Team Dokumentløsninger på:
"Spørsmål **til** koden eller **prosjektet**"

2020-10-12 07:41 UTC, HeidiElisabeth commented on app/pom.xml
>              <version>1.0-SNAPSHOT</version>
Fikser du opp i dette også, Tim?

2020-10-12 07:41 UTC, HeidiElisabeth commented on app/src/test/java/no/nav/doknotifikasjon/TestKafkaEventProducer.java
> +    public void TestDokEventProducer() throws InterruptedException {
Hva gjør egentlig denne testen? Får du inn noen asserts her?

2020-10-12 07:41 UTC, HeidiElisabeth commented on app/src/test/java/no/nav/doknotifikasjon/itest/EmbededKafkaBrokerAbstract.java
> +public class EmbededKafkaBrokerAbstract {
Skal dette egentlig være en abstract class?

2020-10-12 07:41 UTC, HeidiElisabeth commented on core/pom.xml
> +            <version>5.7.0</version>
Versjon skal i rotpommen

2020-10-12 07:41 UTC, HeidiElisabeth commented on core/pom.xml
>              <version>2.3.1.RELEASE</version>
Versjon skal i rotpommen

2020-10-12 07:41 UTC, HeidiElisabeth commented on core/src/main/java/no/nav/doknotifikasjon/exception/technical/DoknotifikasjonTechnicalException.java
> +public class DoknotifikasjonTechnicalException extends RuntimeException {
Du kan godt gjøre denne Abstract - se i andre applikasjoner hvordan vi bruker å gjøre det :)

2020-10-12 07:43 UTC, TimAa-nav-dev commented on README.md
> +Avro skjema se til dette repo: [avro skjema](https://github.com/navikt/doknotifikasjon-schemas)
Jeg tekte å linke til avro skjemo repo, hvor det står i mer detaljer der

2020-10-12 07:47 UTC, TimAa-nav-dev commented on README.md
> +For produsere kafka meldinger, må man først exec inn på kafka kontaineren ved å bruker docker dashbord, eller ved å kjøre følgende kommando:
fikset

2020-10-12 07:47 UTC, TimAa-nav-dev commented on README.md
> +For å kjøre applikasjon kjør med profile local, med system variabler fra her: [System variabler](https://vault.adeo.no/ui/vault/secrets/secret/show/dokument/doknotifikasjon)
fikset

2020-10-12 07:47 UTC, TimAa-nav-dev commented on README.md
> +Lokal utvikling er satt opp slikt at applikasjonen kjøres lokalt og kobles til kafka miljø via et oppsett å docker.
fikset

2020-10-12 07:47 UTC, TimAa-nav-dev commented on README.md
> +Tjenestene har ikke noe forhold på inneholdt til feltet epostTekst og smsTekst.
fikset

2020-10-12 07:48 UTC, TimAa-nav-dev commented on README.md
> +Avro skjema se til dette repo: [avro skjema](https://github.com/navikt/doknotifikasjon-schemas)
Men jeg kan skrive en kort intro for avro

2020-10-12 08:05 UTC, TimAa-nav-dev commented on core/pom.xml
> +            <artifactId>junit</artifactId>
Fikset med å fjerne

2020-10-12 08:12 UTC, TimAa-nav-dev commented on core/pom.xml
>              <version>2.3.1.RELEASE</version>
Fikset

2020-10-12 08:32 UTC, TimAa-nav-dev commented on app/src/test/java/no/nav/doknotifikasjon/itest/EmbededKafkaBrokerAbstract.java
> +public class EmbededKafkaBrokerAbstract {
Fikset

2020-10-12 12:05 UTC, TimAa-nav-dev commented on app/src/test/java/no/nav/doknotifikasjon/TestKafkaEventProducer.java
> +    public void TestDokEventProducer() throws InterruptedException {
Den testen er ikke ferdig, venter når jeg for utviklet mer av knot001

2020-10-12 12:27 UTC, HeidiElisabeth requested changes

2020-10-12 12:27 UTC, HeidiElisabeth commented on README.md
> +tjenesten har ikke noe forhold på innholdt til feltet epostTekst og smsTekst.
Jeg skjønner ikke hva du mener med denne setningen?

2020-10-12 12:27 UTC, HeidiElisabeth commented on README.md
> +Push/merge til master branche vil teste, bygge og deploye til produksjonsmiljø og testmiljø.
branch

2020-10-12 12:27 UTC, HeidiElisabeth commented on README.md
> +Lokal utvikling er satt opp slikt at applikasjonen kjøres lokalt og kobles til kafka miljø via et oppsett på docker.
slik

2020-10-12 12:27 UTC, HeidiElisabeth commented on README.md
> +For å kjøre applikasjon kjør med profile local, med systemvariabler hentet fra vault: [System variabler](https://vault.adeo.no/ui/vault/secrets/secret/show/dokument/doknotifikasjon)
"For å kjøre opp applikasjonen lokal, bruk profile 'local'...."

2020-10-12 12:27 UTC, HeidiElisabeth commented on README.md
> +Avro skjemaløsning blir brukt til å sørge for hva vi consumer og produser på kafka topic har specefikt struktur. Hvis ikke Avro blir brukt, så blir det sendt et JSON object. Avro skjema se til dette
"Avro skjemaløsning blir brukt **for** å sørge for **at det** vi consumer og produser på kafka topic har specefikt struktur"

2020-10-12 12:27 UTC, HeidiElisabeth commented on app/src/test/java/no/nav/doknotifikasjon/Knoot001IntegrationTest.java
> +    public void TestPosetivConsumer() throws InterruptedException {
"PositivConsumerTest" - hva gjør denne testen?

2020-10-12 12:27 UTC, HeidiElisabeth commented on core/pom.xml
> +			<version>1.2.5.RELEASE</version>
Versjoner skal i rotpom :)

2020-10-12 12:27 UTC, HeidiElisabeth commented on core/src/main/java/no/nav/doknotifikasjon/KafkaProducer/KafkaEventProducer.java
>  //@Component
Denne kan sikkert kommenteres inn igjen nå :) Noe jeg gjorde for å kjøre opp lokalt hos meg.

2020-10-12 12:27 UTC, HeidiElisabeth commented on core/src/main/java/no/nav/doknotifikasjon/KafkaProducer/ProducerController.java
>  //@RestController
Kommenter inn igjen :)

2020-10-12 12:27 UTC, HeidiElisabeth commented on core/src/main/java/no/nav/doknotifikasjon/config/KafkaErrorHandler.java
> +        meterRegistry.counter("dok_exception", "type", "technical", "exception_name", exceptionName).increment();
Lurer fortsatt på dette?

2020-10-12 12:27 UTC, HeidiElisabeth commented on docker/CODEOWNERS
> +* @navikt/integrasjon
Husk denne også

2020-10-12 12:27 UTC, HeidiElisabeth commented on knot001/src/main/java/domain/Doknotifikasjon.java
> +    public String getFodselsnummer() {
Du kan heller bruke annotasjonen @Getter og @Setter

2020-10-12 12:27 UTC, HeidiElisabeth commented on knot001/src/main/java/domain/Doknotifikasjon.java
> +    public String getFodselsnummer() {
Da trenger du ingen av get/set metodene

2020-10-12 12:27 UTC, HeidiElisabeth commented on knot001/src/main/java/no/nav/doknotifikasjon/consumer/KafkaEventConsumer.java
> +// ((GenericData.Record) record.value).toString()1
Utkommentert kode?

2020-10-12 12:27 UTC, HeidiElisabeth commented on knot001/src/main/java/no/nav/doknotifikasjon/consumer/KafkaEventConsumer.java
>  //@Component
Kommenter inn igjen

2020-10-12 12:27 UTC, HeidiElisabeth commented on pom.xml
> +        <logstash-logback-encoder.version>5.1</logstash-logback-encoder.version>
Disse linjene står på en annen linje?

2020-10-12 12:43 UTC, TimAa-nav-dev commented on README.md
> +tjenesten har ikke noe forhold på innholdt til feltet epostTekst og smsTekst.
Jeg menner at det som sblir sendti tekst som sms og epost forholder ikke vi oss til, fek hvis det er feilskrevet etc i sms teksten.

2020-10-12 12:44 UTC, TimAa-nav-dev commented on README.md
> +Push/merge til master branche vil teste, bygge og deploye til produksjonsmiljø og testmiljø.
Fikset

2020-10-12 12:44 UTC, TimAa-nav-dev commented on README.md
> +Lokal utvikling er satt opp slikt at applikasjonen kjøres lokalt og kobles til kafka miljø via et oppsett på docker.
fikset

2020-10-12 12:46 UTC, TimAa-nav-dev commented on README.md
> +Avro skjemaløsning blir brukt til å sørge for hva vi consumer og produser på kafka topic har specefikt struktur. Hvis ikke Avro blir brukt, så blir det sendt et JSON object. Avro skjema se til dette
Fikset

2020-10-12 12:47 UTC, TimAa-nav-dev commented on knot001/src/main/java/no/nav/doknotifikasjon/consumer/KafkaEventConsumer.java
>  //@Component
Fikset

2020-10-12 12:49 UTC, TimAa-nav-dev commented on pom.xml
> +        <logstash-logback-encoder.version>5.1</logstash-logback-encoder.version>
Fikset

2020-10-12 12:49 UTC, TimAa-nav-dev commented on knot001/src/main/java/no/nav/doknotifikasjon/consumer/KafkaEventConsumer.java
> +// ((GenericData.Record) record.value).toString()1
Fjernet

2020-10-12 12:51 UTC, TimAa-nav-dev commented on knot001/src/main/java/domain/Doknotifikasjon.java
> +    public String getFodselsnummer() {
Da har jeg lagt  til @getter og @Setter

2020-10-12 12:51 UTC, TimAa-nav-dev commented on README.md
> +For å kjøre applikasjon kjør med profile local, med systemvariabler hentet fra vault: [System variabler](https://vault.adeo.no/ui/vault/secrets/secret/show/dokument/doknotifikasjon)
Rettet opp

2020-10-12 13:02 UTC, HeidiElisabeth commented on README.md
> +tjenesten har ikke noe forhold på innholdt til feltet epostTekst og smsTekst.
Åja! Hva med: "Tjenesten validerer kun at feltene epostTekst og smsTekst er satt. Det er ikke validering på selve innholdet til feltene epostTekst og smsTekst"

2020-10-12 13:12 UTC, TimAa-nav-dev commented on core/src/main/java/no/nav/doknotifikasjon/KafkaProducer/ProducerController.java
>  //@RestController
KAFKA_TOPIC_DOK_NOTIFKASJON er korrekt, forkortet topic name

2020-10-12 13:18 UTC, merged